### 获取日中词典单词列表
GET {{host}}/jc/list?page=1&pageSize=10&val=子供
Authorization: {{token}}
Content-Type: application/json


### 获取单词详情
GET {{host}}/jc/info?id=30033
Authorization: {{token}}
Content-Type: application/json


### 获取跟读列表
GET {{host}}/read?page=1&pageSize=10&id=152807
Authorization: {{token}}
Content-Type: application/json


### 点赞
POST {{host}}/like
Authorization: {{token}}
Content-Type: application/json

{
  "type": "read",
  "id": 20
}


### 获取单词书
GET {{host}}/book/list
Authorization: {{token}}
Content-Type: application/json


### 获取单词书的单词列表
GET {{host}}/word/list?id=1&tab=0&page=1&pageSize=10
Authorization: {{token}}
Content-Type: application/json


### 获取语法列表
GET {{host}}/grammar/list?val=ない&page=1&pageSize=10
Authorization: {{token}}
Content-Type: application/json


### 获取语法详情
GET {{host}}/grammar/info?id=41
Authorization: {{token}}
Content-Type: application/json


### 获取新单词
GET {{host}}/learn
Authorization: {{token}}
Content-Type: application/json


### 获取今日复习的单词
GET {{host}}/review
Authorization: {{token}}
Content-Type: application/json


### 学习&复习单词
POST {{host}}/review
Authorization: {{token}}
Content-Type: application/json

{
  "word_id": 47959,
  "quality": 5
}


### 获取首页信息
GET {{host}}/homeinfo
Authorization: {{token}}
Content-Type: application/json


### 获取含有该单词的单词书id
GET {{host}}/book/word?wordId=64209
Authorization: {{token}}
Content-Type: application/json

# ### 新增单词书
# POST {{host}}/book/add
# Authorization: {{token}}
# Content-Type: application/json

# {
#   "name": "red",
#   "describe": "111",
#   "icon":"sss"
# }

# ### 删除引用
# DELETE {{host}}/notes/quote/1
# Authorization: {{token}}
# Content-Type: application/json


# ### 获取笔记详情
# GET {{host}}/notes/info/152807
# Authorization: {{token}}
# Content-Type: application/json


# ### 排行榜
# GET {{host}}/ranking
# Content-Type: application/json


# ### 日中单词搜索
# GET {{host}}/jc/search/1/10/子供
# Authorization: {{token}}
# Content-Type: application/json


# ### 获取学习信息
# GET {{host}}/learn/info
# Authorization: {{token}}
# Content-Type: application/json


# ### 更新学习记录
# POST {{host}}/learn/record/update
# Authorization: {{token}}
# Content-Type: application/json

# {
#   "words": [
#     {
#       "error": 0,
#       "word_id": 258455
#     },
#     {
#       "error": 0,
#       "word_id": 40024
#     },
#     {
#       "error": 0,
#       "word_id": 223330
#     },
#     {
#       "error": 0,
#       "word_id": 14279
#     },
#     {
#       "error": 0,
#       "word_id": 201604
#     }
#   ]
# }